add bind mount for /etc/hosts
Some developer(or Jenkins) add mirror information to their /etc/hosts file.
But, current script not support for bind mount for hosts file.

To use fed-artik-build in Jenkins, we need to support above feature.
if not, fail in fed-artik-init-buildsys step with below error message.

Cannot download
'http://download1.rpmfusion.org/free/fedora/updates/24/armhfp/': Cannot
download repomd.xml: Cannot download repodata/repomd.xml: All mirrors
were tried.

Change-Id: Icf1e2ea6796a6b83ac6cea3e17546777ee063138
Signed-off-by: Inho Oh <inho48.oh@samsung.com>

diff --git a/chroot_fedora b/chroot_fedora
--- a/chroot_fedora
+++ b/chroot_fedora
@@ -182,6 +182,12 @@ chroot_add_resolv_conf() {
 	chroot_add_mount /etc/resolv.conf "$resolv_conf" --bind
 }
 
+chroot_add_hosts() {
+	local chrootdir=$1 hosts=$1/etc/hosts
+
+	chroot_add_mount /etc/hosts "$hosts" --bind
+}
+
 check_create_user()
 {
 	local COMMANDS=
@@ -231,6 +237,8 @@ package_check qemu-arm-static
 
 chroot_setup "$chrootdir" || die "failed to setup chroot %s" "$chrootdir"
 chroot_add_resolv_conf "$chrootdir" || die "failed to setup resolv.conf"
+chroot_add_hosts "$chrootdir" || die "failed to setup hosts"
+
 [ "$ARCH" == "" ] && detect_arch
 
 if [ "$ARCH" == "armv7hl" ]; then
