support fedora git build
The fedora git is consists of sources, spec and patch files.
It does not contain a source file. Thus, we have to download
the source file using spectool.

Change-Id: I77abd5095fe4715c5184d4bb86d3f0daa94c9f4c
Signed-off-by: Chanho Park <chanho61.park@samsung.com>

diff --git a/fed-artik-build b/fed-artik-build
--- a/fed-artik-build
+++ b/fed-artik-build
@@ -6,8 +6,11 @@ BUILDARCH=armv7hl
 INCLUDE_ALL=
 DEFINE=
 SPECFILE=
+SPECDIR=packaging
 CLEAN_REPOS=false
 CLEAN_REPOS_AND_EXIT=false
+FEDORA_GIT=false
+DOWNLOAD_SOURCE=false
 
 SRC_DIR=/root/rpmbuild/SOURCES
 SPEC_DIR=/root/rpmbuild/SPECS
@@ -166,11 +169,14 @@ run_rpmbuild()
 	local local_repo=$2
 	local spec_base=$(basename "$SPECFILE")
 	local build_cmd="rm -rf /var/cache/dnf/local*; dnf makecache;"
-	build_cmd+="dnf -y --best --allowerasing builddep $SPEC_DIR/$spec_base; rpmbuild --target=$BUILDARCH -ba"
+	if $DOWNLOAD_SOURCE; then
+		build_cmd+="spectool -g -R $SRC_DIR/$spec_base;"
+	fi
+	build_cmd+="dnf -y --best --allowerasing builddep $SRC_DIR/$spec_base; rpmbuild --target=$BUILDARCH -ba"
 	if [ "$DEFINE" != "" ]; then
 		build_cmd+=" --define \"$DEFINE\""
 	fi
-	build_cmd+=" $SPEC_DIR/$spec_base"
+	build_cmd+=" $SRC_DIR/$spec_base"
 
 	sudo -H $SCRIPT_DIR/chroot_fedora -b $local_repo $scratch_root "$build_cmd"
 }
@@ -193,8 +199,26 @@ copy_output_rpms()
 
 detect_spec_file()
 {
-	SPECFILE=`find ./packaging -name "*.spec"`
-	[ -e $SPECFILE ] || die "not found spec file"
+	specfile=`find $SPECDIR -name "*.spec"`
+	if [ "$specfile" == "" ]; then
+		SPECDIR=`pwd`
+		specfile=`find $SPECDIR -name "*.spec"`
+	fi
+
+	[ -e $specfile ] || die "not found spec file"
+
+	SPECFILE=$specfile
+}
+
+detect_fedora_git()
+{
+	if [ -e $SPECDIR/sources ]; then
+		SOURCE=`cat $SPECDIR/sources | awk '{ print $2 }'`
+		if [ ! -e $SPECDIR/$SOURCE ]; then
+			DOWNLOAD_SOURCE=true
+		fi
+		FEDORA_GIT=true
+	fi
 }
 
 BUILDCONFIG="${BUILDCONFIG/#\~/$(eval echo ~$SUDO_USER)}"
@@ -216,11 +240,17 @@ if $CLEAN_REPOS ; then
 	fi
 fi
 
-detect_spec_file
+if [ "$SPECFILE" == "" ]; then
+	detect_spec_file
+fi
 parse_pkg_info
-archive_git_source $SCRATCH_ROOT/$SRC_DIR
 
-sudo cp -f `readlink -e $SPECFILE` $SCRATCH_ROOT/$SPEC_DIR
+detect_fedora_git
+if ! $FEDORA_GIT; then
+	archive_git_source $SCRATCH_ROOT/$SRC_DIR
+fi
+
+sudo cp -f $SPECDIR/* $SCRATCH_ROOT/$SRC_DIR
 
 setup_local_repo $SCRATCH_ROOT $LOCAL_REPO
 if [ "$REPO_URL" != "" ]; then
